# Generated by Django 3.0.5 on 2021-06-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('field', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('fieldDesc', models.TextField(default='')),
                ('profile', models.ImageField(blank=True, default='', max_length=300, null=True, upload_to='Profile/')),
                ('birthdate', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, default='', null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('degree', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('mail', models.EmailField(blank=True, default='', max_length=50, null=True)),
                ('about', models.TextField(default='')),
            ],
        ),
    ]
