# Generated by Django 3.0.5 on 2021-06-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_education_experience_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='university',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
