# Generated by Django 3.0.5 on 2021-06-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20210627_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='percentage',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
