# Generated by Django 3.0.5 on 2021-06-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20210627_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='websiteUrl',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
