# Generated by Django 3.0.5 on 2021-06-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_experience_websiteurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='desc2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experience',
            name='desc3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experience',
            name='desc4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experience',
            name='desc5',
            field=models.TextField(blank=True, default=''),
        ),
    ]
